### ISSUE TITLE
Consider catching error if the response from SPARQL endpoint is not valid RDF

### ISSUE THREAD

**Issue by sklarman** [epistemik-co/staple-api#60]
When there're no matches to a given query, the DBpedia SPARQL endpoint instead of returning an empty payload returns a comment `# Empty NT`. This is essentially wrong but that's how it is, and we should prepare for it. Cause otherwise we get an error:

```
[error]:    uncaughtException: invalid statement:
Virtuoso 37000 Error SP030: SPARQL compiler, line
  ^ starting here
Error: invalid statement:
Virtuoso 37000 Error SP030: SPARQL compiler, line
  ^ starting here
    at reader._error (C:\Users\szymo\OneDrive\Documents\GitHub\staple-api\node_modules\@graphy\content.nq.read\main.js:312:9)
    at reader.safe_parse (C:\Users\szymo\OneDrive\Documents\GitHub\staple-api\node_modules\@graphy\content.nq.read\main.js:467:12)
    at NQuads_Reader.transform [as _transform] (C:\Users\szymo\OneDrive\Documents\GitHub\staple-api\node_modules\@graphy\content.nq.read\main.js:210:11)    at NQuads_Reader.Transform._read (_stream_transform.js:191:10)
    at NQuads_Reader.Transform._write (_stream_transform.js:179:12)
    at doWrite (_stream_writable.js:441:12)
    at writeOrBuffer (_stream_writable.js:425:5)
    at NQuads_Reader.Writable.write (_stream_writable.js:316:11)
    at NQuads_Reader.Writable.end (_stream_writable.js:623:10)
    at Timeout._onTimeout (C:\Users\szymo\OneDrive\Documents\GitHub\staple-api\node_modules\@graphy\content.nq.read\main.js:300:19) {
  "error": {},
  "stack": "Error: invalid statement:\nVirtuoso 37000 Error SP030: SPARQL compiler, line \n  ^ starting here\n    at reader._error (C:\\Users\\szymo\\OneDrive\\Documents\\GitHub\\staple-api\\node_modules\\@graphy\\content.nq.read\\main.js:312:9)\n    at reader.safe_parse (C:\\Users\\szymo\\OneDrive\\Documents\\GitHub\\staple-api\\node_modules\\@graphy\\content.nq.read\\main.js:467:12)\n    at NQuads_Reader.transform [as _transform] (C:\\Users\\szymo\\OneDrive\\Documents\\GitHub\\staple-api\\node_modules\\@graphy\\content.nq.read\\main.js:210:11)\n    at NQuads_Reader.Transform._read (_stream_transform.js:191:10)\n    at NQuads_Reader.Transform._write (_stream_transform.js:179:12)\n    at doWrite (_stream_writable.js:441:12)\n    at writeOrBuffer (_stream_writable.js:425:5)\n    at NQuads_Reader.Writable.write (_stream_writable.js:316:11)\n    at NQuads_Reader.Writable.end (_stream_writable.js:623:10)\n    at Timeout._onTimeout (C:\\Users\\szymo\\OneDrive\\Documents\\GitHub\\staple-api\\node_modules\\@graphy\\content.nq.read\\main.js:300:19)", 
```

Perhaps we could catch the errors coming from uploading RDF to graphy, and just carry on as if the response was empty..?

**Comment by anvime** [comment]
merged bug fix branch
